# IMPORT NOTE: Return code `1` is reserved for exceptions
PIT_CODE_GIT_NOT_FOUND=2
PIT_CODE_GIT_NO_REPO=3

PIT_CODE_INIT_FAILED=10
PIT_CODE_REPO_EXISTS=11

PIT_CODE_REPO_NOT_FOUND=20
PIT_CODE_REPO_LOAD_FAILED=21

PIT_CODE_SNAPSHOT_ABORTED=30
PIT_CODE_STASH_PUSH_FAILED=31
PIT_CODE_STASH_POP_FAILED=32
PIT_CODE_COMMIT_PARSE_FAILED=33

PIT_CODE_ID_NOT_FOUND=40